# Generated by Django 6.1 on 2026-08-12 17:23

import core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0003_post_link_preview'),
        ('stories', '0003_story_link_preview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigIntegerField(default=core.ids.snowflake, editable=False, primary_key=True, serialize=False)),
                ('verb', models.CharField(choices=[('like', 'Liked your post'), ('comment', 'Commented on your post'), ('follow', 'Started following you'), ('follow_request', 'Asked to follow you'), ('repost', 'Reposted your post'), ('story_reaction', 'Reacted to your story'), ('mention', 'Mentioned you')], max_length=20)),
                ('detail', models.CharField(blank=True, max_length=32)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_caused', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='posts.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='posts.post')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='stories.story')),
            ],
            options={
                'db_table': 'notifications',
                'indexes': [models.Index(fields=['recipient', '-id'], name='notifications_recipient'), models.Index(fields=['recipient', 'read_at'], name='notifications_unread')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('comment__isnull', True), ('post__isnull', False)), fields=('recipient', 'actor', 'verb', 'post'), name='notifications_unique_post_verb')],
            },
        ),
    ]
