"""Snowflake IDs — 64-bit, time-sortable, generated by the application.

Every primary key in Aperture is one of these, held in a `BigIntegerField`
with `default=snowflake`. Deliberately **not** `BigAutoField`: the whole point
is that the application owns the value, so an ID can be minted before the row
is written and referenced across a transaction boundary.

What it buys, per `01-ARCHITECTURE.md` §5:

- `ORDER BY id` *is* `ORDER BY created_at`, so cursor pagination is a `WHERE
  id < ?` and nothing more.
- Index locality survives at scale, which UUIDv4 destroys by design.
- No round trip to the database to learn what a row's ID will be.

Layout, most significant bit first::

    0    41 bits            10 bits    12 bits
    |    timestamp (ms)     node       sequence
    ^ unused sign bit

63 significant bits, so every value is a positive signed 64-bit integer and
fits Postgres `bigint` with the sign bit to spare. The 41-bit millisecond
field covers ~69 years from the epoch below, to 2095.
"""

from __future__ import annotations

import os
import threading
import time
from dataclasses import dataclass

__all__ = [
    "EPOCH_MS",
    "MAX_NODE_ID",
    "MAX_SEQUENCE",
    "ClockMovedBackwardsError",
    "SnowflakeGenerator",
    "SnowflakeParts",
    "decode",
    "snowflake",
    "timestamp_ms_of",
]

# 2026-01-01T00:00:00Z. Chosen after the project started so the full 69-year
# range is ahead of us rather than half-spent. Changing this value after any
# row exists reorders every ID in the system — it is permanent.
EPOCH_MS = 1_767_225_600_000

TIMESTAMP_BITS = 41
NODE_BITS = 10
SEQUENCE_BITS = 12

MAX_NODE_ID = (1 << NODE_BITS) - 1
MAX_SEQUENCE = (1 << SEQUENCE_BITS) - 1
MAX_TIMESTAMP = (1 << TIMESTAMP_BITS) - 1

NODE_SHIFT = SEQUENCE_BITS
TIMESTAMP_SHIFT = SEQUENCE_BITS + NODE_BITS

#: Environment variable naming this process's node. Every API and worker
#: process that mints IDs must have a distinct value, or two processes can
#: produce the same ID within the same millisecond.
NODE_ID_ENV_VAR = "SNOWFLAKE_NODE_ID"


class ClockMovedBackwardsError(RuntimeError):
    """The system clock went backwards past a timestamp we have already used.

    Waiting it out is the only safe response — minting anyway would hand out
    IDs that collide with ones already in the database. This is raised rather
    than slept through when the drift is large enough to look like an NTP step
    rather than jitter.
    """


@dataclass(frozen=True, slots=True)
class SnowflakeParts:
    """A decoded snowflake. For debugging and tests, never a hot path."""

    timestamp_ms: int
    node_id: int
    sequence: int


class SnowflakeGenerator:
    """Thread-safe generator for one node.

    Instances are cheap, but you want exactly one per process — see the
    module-level `snowflake()` below, which is the thing models actually use.
    """

    #: Backwards clock drift under this many milliseconds is treated as
    #: ordinary jitter and waited out. Anything larger raises.
    MAX_TOLERATED_DRIFT_MS = 5_000

    def __init__(self, node_id: int, *, epoch_ms: int = EPOCH_MS) -> None:
        if not 0 <= node_id <= MAX_NODE_ID:
            raise ValueError(
                f"node_id must be between 0 and {MAX_NODE_ID}, got {node_id}"
            )
        self._node_id = node_id
        self._epoch_ms = epoch_ms
        self._lock = threading.Lock()
        self._last_timestamp_ms = -1
        self._sequence = 0

    @property
    def node_id(self) -> int:
        return self._node_id

    def next_id(self) -> int:
        """Mint the next ID. Monotonic within this process, thread-safe."""
        with self._lock:
            now = self._now_ms()

            if now < self._last_timestamp_ms:
                drift = self._last_timestamp_ms - now
                if drift > self.MAX_TOLERATED_DRIFT_MS:
                    raise ClockMovedBackwardsError(
                        f"clock moved backwards by {drift}ms; refusing to mint "
                        f"IDs that may already exist"
                    )
                now = self._wait_until(self._last_timestamp_ms)

            if now == self._last_timestamp_ms:
                # Same millisecond: take the next slot, or spin to the next
                # millisecond if we have burned all 4096 of them.
                self._sequence = (self._sequence + 1) & MAX_SEQUENCE
                if self._sequence == 0:
                    now = self._wait_until(self._last_timestamp_ms + 1)
            else:
                self._sequence = 0

            self._last_timestamp_ms = now

            elapsed = now - self._epoch_ms
            if elapsed < 0:
                raise ValueError(
                    "current time is before the snowflake epoch; check the system clock"
                )
            if elapsed > MAX_TIMESTAMP:
                raise OverflowError(
                    "snowflake timestamp field is exhausted; the 41-bit range "
                    "ran out and the layout needs revisiting"
                )

            return (
                (elapsed << TIMESTAMP_SHIFT)
                | (self._node_id << NODE_SHIFT)
                | self._sequence
            )

    def _now_ms(self) -> int:
        return time.time_ns() // 1_000_000

    def _wait_until(self, target_ms: int) -> int:
        now = self._now_ms()
        while now < target_ms:
            time.sleep(0)
            now = self._now_ms()
        return now


def decode(value: int, *, epoch_ms: int = EPOCH_MS) -> SnowflakeParts:
    """Split a snowflake back into its three fields."""
    return SnowflakeParts(
        timestamp_ms=(value >> TIMESTAMP_SHIFT) + epoch_ms,
        node_id=(value >> NODE_SHIFT) & MAX_NODE_ID,
        sequence=value & MAX_SEQUENCE,
    )


def timestamp_ms_of(value: int, *, epoch_ms: int = EPOCH_MS) -> int:
    """Unix milliseconds encoded in `value`.

    Handy because it means a row's creation time is recoverable from its ID
    alone, with no column read.
    """
    return (value >> TIMESTAMP_SHIFT) + epoch_ms


def _node_id_from_env() -> int:
    raw = os.environ.get(NODE_ID_ENV_VAR)
    if raw is None or raw == "":
        # Single-process local development. Every deployed process must set
        # the variable explicitly; see `.env.example`.
        return 0
    try:
        node_id = int(raw)
    except ValueError as exc:
        raise ValueError(f"{NODE_ID_ENV_VAR} must be an integer, got {raw!r}") from exc
    if not 0 <= node_id <= MAX_NODE_ID:
        raise ValueError(
            f"{NODE_ID_ENV_VAR} must be between 0 and {MAX_NODE_ID}, got {node_id}"
        )
    return node_id


_generator = SnowflakeGenerator(_node_id_from_env())


def snowflake() -> int:
    """Mint an ID from this process's generator.

    This is the callable every model's primary key defaults to. Django's
    migration serializer records it by import path, so it must stay importable
    as `core.ids.snowflake` — moving or renaming it rewrites every migration.
    """
    return _generator.next_id()
