# Generated by Django 6.1 on 2026-08-12 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_messagehidden'),
        ('posts', '0004_post_reposted_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='shared_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_in_messages', to='posts.post'),
        ),
    ]
