# Generated by Django 6.1 on 2026-08-12 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_message_shared_post'),
        ('stories', '0004_storyreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='replied_story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='stories.story'),
        ),
    ]
