# Generated by Django 6.1 on 2026-08-11 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0002_initial'),
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.comment'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post'),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_attachments', to='media.media'),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='posts.post'),
        ),
        migrations.AddField(
            model_name='timelineentry',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_authored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timelineentry',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='posts.post'),
        ),
        migrations.AddField(
            model_name='timelineentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-id'], name='posts_author_id_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(models.OrderBy(models.F('id'), descending=True), condition=models.Q(('deleted_at__isnull', True)), name='posts_live_id_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user', '-created_at'], name='likes_user_created_desc_idx'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='likes_unique'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'id'], name='comments_post_id_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent', 'id'], name='comments_parent_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='postmedia',
            constraint=models.UniqueConstraint(fields=('post', 'position'), name='post_media_unique_position'),
        ),
        migrations.AddConstraint(
            model_name='postmedia',
            constraint=models.UniqueConstraint(fields=('post', 'media'), name='post_media_unique_media'),
        ),
        migrations.AddIndex(
            model_name='timelineentry',
            index=models.Index(fields=['user', '-created_at'], name='timeline_user_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='timelineentry',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='timeline_unique'),
        ),
    ]
