# Generated by Django 6.1 on 2026-08-11 20:51

import core.ids
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigIntegerField(default=core.ids.snowflake, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('user', 'User'), ('media', 'Media')], max_length=10)),
                ('subject_id', models.BigIntegerField()),
                ('reason', models.CharField(choices=[('csam', 'Child sexual abuse material'), ('violence', 'Violence or threats'), ('harassment', 'Harassment or bullying'), ('hate', 'Hate speech'), ('nudity', 'Adult nudity or sexual activity'), ('spam', 'Spam or scam'), ('self_harm', 'Self-harm or suicide'), ('copyright', 'Copyright or trademark'), ('other', 'Something else')], max_length=20)),
                ('note', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], default='open', max_length=10)),
                ('resolution_note', models.TextField(blank=True, max_length=1000)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('reporter', models.ForeignKey(blank=True, help_text='Null once the reporting account is deleted.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL)),
                ('subject_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_against', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
                'indexes': [models.Index(fields=['status', '-id'], name='reports_status_id_desc_idx'), models.Index(fields=['subject_type', 'subject_id'], name='reports_subject_idx'), models.Index(fields=['subject_owner'], name='reports_owner_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('reporter', 'subject_type', 'subject_id'), name='reports_one_open_per_reporter')],
            },
        ),
    ]
