# Generated by Django 6.1 on 2026-08-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='subject_type',
            field=models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('user', 'User'), ('media', 'Media'), ('message', 'Message')], max_length=10),
        ),
    ]
