# Generated by Django 6.1 on 2026-08-12 15:16

import core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkPreview',
            fields=[
                ('id', models.BigIntegerField(default=core.ids.snowflake, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('url_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('description', models.CharField(blank=True, max_length=600)),
                ('image_url', models.TextField(blank=True)),
                ('site_name', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'link_previews',
            },
        ),
    ]
