/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/calls/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Answer a call. Membership and blocks are re-checked here rather than trusted from the invite. */
        post: operations["calls_join"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calls/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Start a call in a conversation. Returns ICE servers for every call and a LiveKit room token for group calls, and rings the other participants over their socket. */
        post: operations["calls_start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Liveness and dependency check. Verifies Postgres, Redis and object storage by performing real operations against each. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{media_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description One media row, including its processing state. */
        get: operations["media_retrieve"];
        put?: never;
        post?: never;
        /** @description Soft delete. A scheduled job removes the objects later. */
        delete: operations["media_destroy"];
        options?: never;
        head?: never;
        /** @description Set alt text. May be empty — the field is always present, but never required. */
        patch: operations["media_set_alt_text"];
        trace?: never;
    };
    "/api/media/{media_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Signal that the browser finished its PUT. Enqueues validation and derivative generation. Poll the detail endpoint until state leaves 'pending'. */
        post: operations["media_complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/intent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Reserve a media row and return a presigned URL to PUT the file to. The row is created in state=pending; the bytes go straight to object storage and never through this server. */
        post: operations["media_intent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/messaging/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Conversations you are in, most recently active first. */
        get: operations["messaging_conversations"];
        put?: never;
        /** @description Start a DM or a group. A DM between two people is unique. */
        post: operations["messaging_start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/messaging/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description A window of a conversation, addressed by seq. */
        get: operations["messaging_messages"];
        put?: never;
        /** @description Send a message. Idempotent on client_id: retrying after a timeout returns the message that already exists rather than creating a second one. */
        post: operations["messaging_send"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/messaging/conversations/{conversation_id}/messages/{seq}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Soft delete your own message. */
        delete: operations["messaging_delete_message"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/messaging/conversations/{conversation_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Move your read position forward. Never backward. */
        post: operations["messaging_mark_read"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/moderation/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Report a post, comment, user or piece of media. Idempotent per reporter per subject: reporting twice returns the first report. */
        post: operations["moderation_report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Publish a post from media that has finished processing. */
        post: operations["posts_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description One post. */
        get: operations["posts_retrieve"];
        put?: never;
        post?: never;
        /** @description Soft delete your own post. */
        delete: operations["posts_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{post_id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Top-level comments, oldest first. */
        get: operations["posts_comments_list"];
        put?: never;
        /** @description Comment on a post, or reply to a comment. */
        post: operations["posts_comments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{post_id}/like": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Like a post. Idempotent. */
        post: operations["posts_like"];
        /** @description Remove a like. Idempotent. */
        delete: operations["posts_unlike"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/by/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description One account's posts, newest first. */
        get: operations["posts_by_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/comments/{comment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Soft delete your own comment. */
        delete: operations["posts_comments_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/explore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Recent public posts from accounts you do not follow. */
        get: operations["posts_explore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Posts from accounts you follow, newest first. */
        get: operations["posts_feed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/realtime/ticket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Mint a short-lived signed ticket for the socket gateway. The gateway verifies it locally and never calls back. */
        post: operations["realtime_ticket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description One account's public profile, with its counts. */
        get: operations["users_profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{username}/block": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Block an account, severing follows both ways. */
        post: operations["users_block"];
        /** @description Unblock. Does not restore the follows that blocking severed. */
        delete: operations["users_unblock"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{username}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Follow, or request to follow a private account. */
        post: operations["users_follow"];
        /** @description Unfollow, or withdraw a pending request. */
        delete: operations["users_unfollow"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{username}/respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Approve or decline a pending follow request. */
        post: operations["users_respond_to_request"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The signed-in user. */
        get: operations["users_me"];
        put?: never;
        post?: never;
        /** @description Delete your account. Content disappears from every read path immediately; the rows are erased permanently after a grace period. */
        delete: operations["users_delete_me"];
        options?: never;
        head?: never;
        /** @description Update your own profile. */
        patch: operations["users_update_me"];
        trace?: never;
    };
    "/api/users/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Mail a password reset link. Answers 204 whether or not the address is known. */
        post: operations["users_password_reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/password/reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Complete a password reset and sign every session out. */
        post: operations["users_password_reset_confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create an account. Signs the new account in. */
        post: operations["users_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Pending follow requests for your account. */
        get: operations["users_follow_requests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Find accounts by username or display name. */
        get: operations["users_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Sign in with email and password. */
        post: operations["session_create"];
        /** @description Sign out. Idempotent. */
        delete: operations["session_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Everything a client needs to join a call and nothing it does not. */
        Call: {
            readonly id: string;
            readonly conversation_id: string;
            readonly mode: string;
            readonly participant_ids: string[];
            readonly ice_servers: components["schemas"]["IceServer"][];
            readonly livekit_url: string | null;
            readonly livekit_token: string | null;
        };
        Comment: {
            readonly id: string;
            readonly post_id: string;
            readonly parent_id: string | null;
            readonly author: components["schemas"]["User"];
            readonly body: string;
            /** Format: date-time */
            readonly created_at: string;
            readonly reply_count: number;
        };
        CommentPage: {
            readonly comments: components["schemas"]["Comment"][];
            readonly next_cursor: string | null;
        };
        /** @description A conversation as it appears in the inbox. */
        Conversation: {
            readonly id: string;
            readonly kind: string;
            readonly title: string;
            readonly members: components["schemas"]["User"][];
            readonly last_message_seq: number;
            readonly last_read_seq: number;
            readonly unread_count: number;
            readonly last_message: components["schemas"]["Message"] | null;
        };
        CreateCommentRequest: {
            body: string;
            parent_id?: string | null;
        };
        /** @description Publishing a post from media that is already uploaded and processed. */
        CreatePostRequest: {
            media_ids: string[];
            /** @default  */
            caption: string;
            /** @default  */
            location: string;
            /** @default public */
            visibility: components["schemas"]["VisibilityEnum"];
        };
        CreateReportRequest: {
            subject_type: components["schemas"]["SubjectTypeEnum"];
            subject_id: string;
            reason: components["schemas"]["ReasonEnum"];
            /** @default  */
            note: string;
        };
        /** @description The signed-in user seeing their own account. Adds the private bits. */
        CurrentUser: {
            readonly id: string;
            /** @description Case-insensitively unique. Shown in metadata position. */
            readonly username: string;
            readonly display_name: string;
            readonly avatar_media_id: string | null;
            readonly bio: string;
            /** @description Private accounts turn follows into requests pending approval. */
            readonly is_private: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: email */
            readonly email: string;
        };
        /** @description A pending request, from the perspective of the account being asked. */
        FollowRequest: {
            readonly follower: components["schemas"]["User"];
            /** Format: date-time */
            readonly created_at: string;
        };
        /** @description What the follow button should read after acting. */
        FollowState: {
            readonly follow_state: components["schemas"]["FollowStateEnum"];
        };
        /**
         * @description * `none` - none
         *     * `pending` - pending
         *     * `accepted` - accepted
         * @enum {string}
         */
        FollowStateEnum: "none" | "pending" | "accepted";
        /** @description The whole report. */
        Health: {
            status: components["schemas"]["HealthStatusEnum"];
            checks: components["schemas"]["HealthCheck"][];
        };
        /** @description One dependency's result. */
        HealthCheck: {
            name: string;
            status: components["schemas"]["HealthCheckStatusEnum"];
            /** Format: double */
            latency_ms: number;
            detail: string;
        };
        /**
         * @description * `ok` - ok
         *     * `failing` - failing
         * @enum {string}
         */
        HealthCheckStatusEnum: "ok" | "failing";
        /**
         * @description * `ok` - ok
         *     * `degraded` - degraded
         * @enum {string}
         */
        HealthStatusEnum: "ok" | "degraded";
        /**
         * @description One `RTCIceServer`, handed to the browser verbatim.
         *
         *     `credential` is a TURN password that expires — see `core/turn.py`. It is
         *     not a secret worth protecting for long, which is exactly why it is safe to
         *     send here at all.
         */
        IceServer: {
            readonly urls: string[];
            readonly username: string;
            readonly credential: string;
        };
        /**
         * @description Answering an invite.
         *
         *     `call_id` and `mode` come back from the invite the callee received over
         *     the socket. Neither is trusted for authorization — `join_call` re-checks
         *     membership and blocks against the conversation before minting anything.
         */
        JoinCallRequest: {
            conversation_id: string;
            call_id: string;
            mode: components["schemas"]["ModeEnum"];
        };
        /**
         * @description * `image` - Image
         *     * `video` - Video
         * @enum {string}
         */
        KindEnum: "image" | "video";
        /** @description Credentials. Email is the login identifier here, not username. */
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        MarkReadRequest: {
            up_to_seq: number;
        };
        /**
         * @description A media row as the client sees it.
         *
         *     Everything the develop-in needs is here: `blurhash` for the canvas,
         *     `width`/`height` to reserve the space so nothing shifts, and
         *     `dominant_color` for the ambient glow.
         */
        Media: {
            readonly id: string;
            readonly owner_id: string;
            readonly kind: components["schemas"]["KindEnum"];
            readonly state: components["schemas"]["StateEnum"];
            readonly width: number | null;
            readonly height: number | null;
            readonly duration_ms: number | null;
            readonly blurhash: string;
            readonly dominant_color: string;
            /** @description May be empty, but the composer always presents the field. */
            readonly alt_text: string;
            readonly failure_reason: string;
            /** Format: date-time */
            readonly created_at: string;
            readonly sources: components["schemas"]["MediaSource"][];
            /** Format: uri */
            readonly original_url: string | null;
            /** Format: uri */
            readonly poster_url: string | null;
            /** Format: uri */
            readonly video_url: string | null;
        };
        /** @description One rendition of an image, for a `srcset`. */
        MediaSource: {
            width: number;
            /** Format: uri */
            url: string;
        };
        Message: {
            readonly id: string;
            readonly conversation_id: string;
            readonly seq: number;
            readonly sender: components["schemas"]["User"];
            readonly body: string;
            readonly media: components["schemas"]["Media"] | null;
            /** Format: uuid */
            readonly client_id: string;
            readonly reply_to_seq: number | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        /** @description A window of a conversation, addressed by `seq` rather than by offset. */
        MessagePage: {
            readonly messages: components["schemas"]["Message"][];
            readonly last_message_seq: number;
            readonly oldest_seq: number | null;
        };
        /**
         * @description * `p2p` - p2p
         *     * `sfu` - sfu
         * @enum {string}
         */
        ModeEnum: "p2p" | "sfu";
        /**
         * @description Complete a reset.
         *
         *     `uid` and `token` come straight back out of the link, so they are opaque
         *     strings here — validating their shape would only move the same rejection
         *     earlier and give a probe a way to tell malformed from wrong.
         */
        PasswordResetConfirmRequest: {
            uid: string;
            token: string;
            password: string;
        };
        /** @description Ask for a link. An address, and nothing else. */
        PasswordResetRequestRequest: {
            /** Format: email */
            email: string;
        };
        /** @description Alt text may be empty, but the field is always present. */
        PatchedAltTextRequest: {
            alt_text?: string;
        };
        PatchedUpdateProfileRequest: {
            display_name?: string;
            bio?: string;
            is_private?: boolean;
        };
        /** @description A post as the feed and the contact sheet see it. */
        Post: {
            readonly id: string;
            readonly author: components["schemas"]["User"];
            readonly caption: string;
            readonly location: string;
            readonly visibility: components["schemas"]["VisibilityEnum"];
            /** Format: date-time */
            readonly created_at: string;
            readonly media: components["schemas"]["Media"][];
            readonly like_count: number;
            readonly comment_count: number;
            readonly viewer_has_liked: boolean;
        };
        /**
         * @description A cursor-paginated page of posts.
         *
         *     `next_cursor` is the id of the last post on the page, or null at the end.
         *     No total count: producing one means a `COUNT(*)` over the whole feed, and
         *     nothing in the UI shows it.
         */
        PostPage: {
            readonly posts: components["schemas"]["Post"][];
            readonly next_cursor: string | null;
        };
        /**
         * @description A profile header.
         *
         *     Counts come from the `counters` app, never from a `COUNT(*)` — a follower
         *     count on a popular account is a sequential scan over millions of rows, and
         *     it renders on every profile view.
         *
         *     `follow_state` is what the button reads: absent, `pending` while a private
         *     account considers the request, or `accepted`.
         */
        Profile: {
            readonly user: components["schemas"]["User"];
            readonly post_count: number;
            readonly follower_count: number;
            readonly following_count: number;
            readonly follow_state: components["schemas"]["FollowStateEnum"];
            readonly is_self: boolean;
            readonly can_view_posts: boolean;
        };
        /** @description A short-lived credential for the socket gateway. */
        RealtimeTicket: {
            readonly ticket: string;
            readonly url: string;
            readonly expires_in_seconds: number;
        };
        /**
         * @description * `csam` - Child sexual abuse material
         *     * `violence` - Violence or threats
         *     * `harassment` - Harassment or bullying
         *     * `hate` - Hate speech
         *     * `nudity` - Adult nudity or sexual activity
         *     * `spam` - Spam or scam
         *     * `self_harm` - Self-harm or suicide
         *     * `copyright` - Copyright or trademark
         *     * `other` - Something else
         * @enum {string}
         */
        ReasonEnum: "csam" | "violence" | "harassment" | "hate" | "nudity" | "spam" | "self_harm" | "copyright" | "other";
        /**
         * @description What it takes to open an account.
         *
         *     `username` is constrained here rather than only at the database, because
         *     the model's uniqueness will not tell you that a space is not allowed. The
         *     pattern matches what a profile URL can carry — `/u/<username>` — so a name
         *     that cannot be linked to cannot be chosen.
         */
        RegisterRequest: {
            /** Format: email */
            email: string;
            username: string;
            password: string;
        };
        /**
         * @description A report, as the person who filed it may see it.
         *
         *     Deliberately thin: the reporter learns that their report exists and
         *     nothing about what happened next. Telling them the outcome would tell them
         *     whether the person they reported was actioned, which is a privacy leak
         *     about a third party and, when the reporter is the harasser, a feedback
         *     signal for tuning the next attempt.
         */
        Report: {
            readonly id: string;
            readonly subject_type: components["schemas"]["SubjectTypeEnum"];
            readonly subject_id: string;
            readonly reason: components["schemas"]["ReasonEnum"];
            /** Format: date-time */
            readonly created_at: string;
        };
        RespondToRequestRequest: {
            accept: boolean;
        };
        /**
         * @description What the client sends.
         *
         *     `client_id` is required and minted by the browser. It is the only thing
         *     standing between a flaky network and a duplicated message, so there is no
         *     server-side default — a client that does not send one does not get
         *     idempotency, and should be made to notice.
         */
        SendMessageRequest: {
            /** Format: uuid */
            client_id: string;
            /** @default  */
            body: string;
            media_id?: string | null;
            reply_to_seq?: number | null;
        };
        SendMessageResponse: {
            readonly message: components["schemas"]["Message"];
            readonly created: boolean;
        };
        /** @description Which conversation to ring. */
        StartCallRequest: {
            conversation_id: string;
        };
        StartConversationRequest: {
            usernames: string[];
            /** @default  */
            title: string;
        };
        /**
         * @description * `pending` - Pending
         *     * `ready` - Ready
         *     * `failed` - Failed
         * @enum {string}
         */
        StateEnum: "pending" | "ready" | "failed";
        /**
         * @description * `post` - Post
         *     * `comment` - Comment
         *     * `user` - User
         *     * `media` - Media
         *     * `message` - Message
         * @enum {string}
         */
        SubjectTypeEnum: "post" | "comment" | "user" | "media" | "message";
        /** @description What the client asks for before it uploads anything. */
        UploadIntentRequestRequest: {
            kind: components["schemas"]["KindEnum"];
            mime: string;
            size_bytes: number;
        };
        /** @description The reservation, and the URL to PUT to. */
        UploadIntentResponse: {
            readonly media: components["schemas"]["Media"];
            /** Format: uri */
            readonly upload_url: string;
            readonly expires_in_seconds: number;
        };
        /** @description A user as anyone may see them. No email, no permission flags. */
        User: {
            readonly id: string;
            /** @description Case-insensitively unique. Shown in metadata position. */
            readonly username: string;
            readonly display_name: string;
            readonly avatar_media_id: string | null;
            readonly bio: string;
            /** @description Private accounts turn follows into requests pending approval. */
            readonly is_private: boolean;
            /** Format: date-time */
            readonly created_at: string;
        };
        UserList: {
            readonly users: components["schemas"]["User"][];
        };
        /**
         * @description * `public` - Public
         *     * `followers` - Followers only
         *     * `private` - Private
         * @enum {string}
         */
        VisibilityEnum: "public" | "followers" | "private";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    calls_join: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinCallRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["JoinCallRequest"];
                "multipart/form-data": components["schemas"]["JoinCallRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Call"];
                };
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    calls_start: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartCallRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["StartCallRequest"];
                "multipart/form-data": components["schemas"]["StartCallRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Call"];
                };
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    media_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Media"];
                };
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    media_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    media_set_alt_text: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAltTextRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAltTextRequest"];
                "multipart/form-data": components["schemas"]["PatchedAltTextRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Media"];
                };
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    media_complete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Media"];
                };
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    media_intent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadIntentRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UploadIntentRequestRequest"];
                "multipart/form-data": components["schemas"]["UploadIntentRequestRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadIntentResponse"];
                };
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    messaging_conversations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"][];
                };
            };
        };
    };
    messaging_start: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartConversationRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["StartConversationRequest"];
                "multipart/form-data": components["schemas"]["StartConversationRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    messaging_messages: {
        parameters: {
            query?: {
                /** @description Return everything with a higher seq. This is the whole offline-sync story: 'send me everything after 4821'. */
                after?: number;
                /** @description Scrollback: return messages older than this seq. */
                before?: number;
            };
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessagePage"];
                };
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    messaging_send: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SendMessageRequest"];
                "multipart/form-data": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendMessageResponse"];
                };
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    messaging_delete_message: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
                seq: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    messaging_mark_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkReadRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["MarkReadRequest"];
                "multipart/form-data": components["schemas"]["MarkReadRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    moderation_report: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReportRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CreateReportRequest"];
                "multipart/form-data": components["schemas"]["CreateReportRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    posts_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePostRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CreatePostRequest"];
                "multipart/form-data": components["schemas"]["CreatePostRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"];
                };
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    posts_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"];
                };
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    posts_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    posts_comments_list: {
        parameters: {
            query?: {
                /** @description Snowflake id of the last item on the previous page. Ids are time-ordered, so this is simply 'older than that one'. */
                cursor?: string;
            };
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentPage"];
                };
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    posts_comments_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CreateCommentRequest"];
                "multipart/form-data": components["schemas"]["CreateCommentRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    posts_like: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"];
                };
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    posts_unlike: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"];
                };
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    posts_by_user: {
        parameters: {
            query?: {
                /** @description Snowflake id of the last item on the previous page. Ids are time-ordered, so this is simply 'older than that one'. */
                cursor?: string;
            };
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostPage"];
                };
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    posts_comments_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    posts_explore: {
        parameters: {
            query?: {
                /** @description Snowflake id of the last item on the previous page. Ids are time-ordered, so this is simply 'older than that one'. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostPage"];
                };
            };
        };
    };
    posts_feed: {
        parameters: {
            query?: {
                /** @description Snowflake id of the last item on the previous page. Ids are time-ordered, so this is simply 'older than that one'. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostPage"];
                };
            };
        };
    };
    realtime_ticket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RealtimeTicket"];
                };
            };
        };
    };
    users_profile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_block: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_unblock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_follow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowState"];
                };
            };
            /** @description No response body */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_unfollow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowState"];
                };
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_respond_to_request: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RespondToRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RespondToRequestRequest"];
                "multipart/form-data": components["schemas"]["RespondToRequestRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            /** @description No response body */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_delete_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_update_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUpdateProfileRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUpdateProfileRequest"];
                "multipart/form-data": components["schemas"]["PatchedUpdateProfileRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            /** @description No response body */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_password_reset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetRequestRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetRequestRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_password_reset_confirm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetConfirmRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RegisterRequest"];
                "multipart/form-data": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_follow_requests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowRequest"][];
                };
            };
        };
    };
    users_search: {
        parameters: {
            query: {
                /** @description Query */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserList"];
                };
            };
        };
    };
    session_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LoginRequest"];
                "multipart/form-data": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    session_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
