/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Liveness and dependency check. Verifies Postgres, Redis and object storage by performing real operations against each. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The whole report. */
        Health: {
            status: components["schemas"]["HealthStatusEnum"];
            checks: components["schemas"]["HealthCheck"][];
        };
        /** @description One dependency's result. */
        HealthCheck: {
            name: string;
            status: components["schemas"]["HealthCheckStatusEnum"];
            /** Format: double */
            latency_ms: number;
            detail: string;
        };
        /**
         * @description * `ok` - ok
         *     * `failing` - failing
         * @enum {string}
         */
        HealthCheckStatusEnum: "ok" | "failing";
        /**
         * @description * `ok` - ok
         *     * `degraded` - degraded
         * @enum {string}
         */
        HealthStatusEnum: "ok" | "degraded";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
