# Generated by Django 6.1 on 2026-08-12 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_initial'),
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='background',
            field=models.CharField(blank=True, default='slate', max_length=16),
        ),
        migrations.AddField(
            model_name='story',
            name='text',
            field=models.TextField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='story',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stories', to='media.media'),
        ),
        migrations.AddConstraint(
            model_name='story',
            constraint=models.CheckConstraint(condition=models.Q(('media__isnull', False), models.Q(('text', ''), _negated=True), _connector='OR'), name='stories_have_content'),
        ),
    ]
