# Generated by Django 6.1 on 2026-08-12 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
        ('stories', '0002_story_background_story_text_alter_story_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='link_preview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='links.linkpreview'),
        ),
    ]
