# Generated by Django 6.1 on 2026-08-11 18:21

import core.ids
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigIntegerField(default=core.ids.snowflake, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('bucket', models.CharField(max_length=63)),
                ('object_key', models.CharField(max_length=1024)),
                ('declared_mime', models.CharField(max_length=127)),
                ('declared_size_bytes', models.BigIntegerField()),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('blurhash', models.CharField(blank=True, max_length=64)),
                ('dominant_color', models.CharField(blank=True, max_length=32)),
                ('alt_text', models.CharField(blank=True, help_text='May be empty, but the composer always presents the field.', max_length=1000)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'media',
                'db_table': 'media',
            },
        ),
    ]
