# Generated by Django 6.1 on 2026-08-11 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['owner', '-id'], name='media_owner_id_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['state', 'created_at'], name='media_state_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.UniqueConstraint(fields=('bucket', 'object_key'), name='media_unique_object'),
        ),
    ]
