# Generated by Django 6.1 on 2026-08-11 18:21

import core.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigIntegerField(default=core.ids.snowflake, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('user', 'User'), ('post', 'Post'), ('comment', 'Comment'), ('conversation', 'Conversation')], max_length=20)),
                ('entity_id', models.BigIntegerField()),
                ('metric', models.CharField(choices=[('followers', 'Followers'), ('following', 'Following'), ('posts', 'Posts'), ('likes', 'Likes'), ('comments', 'Comments'), ('replies', 'Replies')], max_length=20)),
                ('value', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'counters',
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'entity_id', 'metric'), name='counters_unique_metric')],
            },
        ),
    ]
