# Generated by Django 6.1 on 2026-08-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='metric',
            field=models.CharField(choices=[('followers', 'Followers'), ('following', 'Following'), ('posts', 'Posts'), ('likes', 'Likes'), ('comments', 'Comments'), ('replies', 'Replies'), ('reposts', 'Reposts'), ('shares', 'Shares')], max_length=20),
        ),
    ]
